/*** Generated by streamline 0.10.9 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func; (function() {
  var Line;

  Line = (function() {
    function Line(connection, table, fields) {
      this.connection = connection;
      this.table = table;
      this.fields = fields; };


    Line.prototype.save = function Line_prototype_save__1(_) { var __frame = { name: "Line_prototype_save__1", line: 11 }; return __func(_, this, arguments, Line_prototype_save__1, 0, __frame, function __$Line_prototype_save__1() { _(); }); };

    return Line;

  })();

}).call(this);
