/*** Generated by streamline 0.10.9 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func; (function() {
  var Line, Query;

  Query = require("./Query");

  Line = (function() {
    function Line(connection, table, columns) {
      this.connection = connection;
      this.table = table;
      this.columns = columns; };


    Line.prototype.save = function Line_prototype_save__1(_) { var __frame = { name: "Line_prototype_save__1", line: 13 }; return __func(_, this, arguments, Line_prototype_save__1, 0, __frame, function __$Line_prototype_save__1() { _(); }); };

    return Line;

  })();

  module.exports = Line;

}).call(this);
