/*** Generated by streamline 0.10.9 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Model, orm;

  Model = require("./Model");

  orm = (function() {
    function orm(connection, _) { var __this = this; var __frame = { name: "orm", line: 7 }; return __func(_, this, arguments, orm, 1, __frame, function __$orm() {
        __this.connection = connection;
        return createTables(__cb(_, __frame, 2, 6, function __$orm() { _(); }, true)); }); };


    orm.prototype.createTables = function orm_prototype_createTables__1(_) { var tables, __this = this; var __frame = { name: "orm_prototype_createTables__1", line: 12 }; return __func(_, this, arguments, orm_prototype_createTables__1, 0, __frame, function __$orm_prototype_createTables__1() {

        return __this.connection.execute("select * from tables", [], __cb(_, __frame, 2, 38, function ___(__0, __2) { var __1 = tables = __2; return _(null, __1); }, true)); }); };


    orm.prototype.execute = function orm_prototype_execute__2(sql, args, _) { var __this = this; var __frame = { name: "orm_prototype_execute__2", line: 17 }; return __func(_, this, arguments, orm_prototype_execute__2, 2, __frame, function __$orm_prototype_execute__2() {
        return __this.connection.execute(sql, args, __cb(_, __frame, 1, 29, _, true)); }); };


    return orm;

  })();

}).call(this);
