/*** Generated by streamline 0.10.9 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Query;

  Query = (function() {
    function Query(connection, table, type, params) {
      this.connection = connection;
      this.table = table;
      this.type = type;
      this.params = params; };


    Query.prototype.run = function Query_prototype_run__1(_) { var __this = this; var __frame = { name: "Query_prototype_run__1", line: 12 }; return __func(_, this, arguments, Query_prototype_run__1, 0, __frame, function __$Query_prototype_run__1() {
        return __this[__this.type](__cb(_, __frame, 1, 13, _, true)); }); };


    Query.prototype.select = function Query_prototype_select__2(_) { var __frame = { name: "Query_prototype_select__2", line: 16 }; return __func(_, this, arguments, Query_prototype_select__2, 0, __frame, function __$Query_prototype_select__2() { _(); }); };

    Query.prototype.update = function Query_prototype_update__3(_) { var __frame = { name: "Query_prototype_update__3", line: 18 }; return __func(_, this, arguments, Query_prototype_update__3, 0, __frame, function __$Query_prototype_update__3() { _(); }); };

    Query.prototype.insert = function Query_prototype_insert__4(_) { var __frame = { name: "Query_prototype_insert__4", line: 20 }; return __func(_, this, arguments, Query_prototype_insert__4, 0, __frame, function __$Query_prototype_insert__4() { _(); }); };

    Query.prototype.del = function Query_prototype_del__5(_) { var __frame = { name: "Query_prototype_del__5", line: 22 }; return __func(_, this, arguments, Query_prototype_del__5, 0, __frame, function __$Query_prototype_del__5() { _(); }); };

    return Query;

  })();

}).call(this);
