/*** Generated by streamline 0.10.9 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func; (function() {
  var Row;

  Row = (function() {
    function Row(connection, table, data) {
      this.connection = connection;
      this.table = table;
      this.data = data; };


    Row.prototype.save = function Row_prototype_save__1(_) { var __frame = { name: "Row_prototype_save__1", line: 11 }; return __func(_, this, arguments, Row_prototype_save__1, 0, __frame, function __$Row_prototype_save__1() { _(); }); };

    return Row;

  })();

  module.exports = Row;

}).call(this);
