/*** Generated by streamline 0.10.9 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Query, Row, Table;

  Row = require("./Row");

  Query = require("./Query");

  Table = (function() {
    function Table(connection, name, columns, joins) {
      this.connection = connection;
      this.name = name;
      this.columns = columns;
      this.joins = joins; };


    Table.prototype.add = function Table_prototype_add__1(pairs, _) { var query, __this = this; var __frame = { name: "Table_prototype_add__1", line: 16 }; return __func(_, this, arguments, Table_prototype_add__1, 1, __frame, function __$Table_prototype_add__1() {

        query = new Query(__this.connection, __this.name);
        return query.insert(pairs, __cb(_, __frame, 3, 19, _, true)); }); };


    Table.prototype.get = function Table_prototype_get__2(where, orderBy, _) { var query, __this = this; var __frame = { name: "Table_prototype_get__2", line: 22 }; return __func(_, this, arguments, Table_prototype_get__2, 2, __frame, function __$Table_prototype_get__2() {

        if ((where == null)) {
          where = { }; } ;

        if ((orderBy == null)) {
          orderBy = null; } ;

        query = new Query(__this.connection, __this.name);
        return query.select(where, orderBy, [], __cb(_, __frame, 9, 19, _, true)); }); };


    Table.prototype.all = function Table_prototype_all__3(_) { var __this = this; var __frame = { name: "Table_prototype_all__3", line: 34 }; return __func(_, this, arguments, Table_prototype_all__3, 0, __frame, function __$Table_prototype_all__3() {
        return __this.get(null, null, __cb(_, __frame, 1, 18, _, true)); }); };


    Table.prototype.getById = function Table_prototype_getById__4(IDs, _) { var __frame = { name: "Table_prototype_getById__4", line: 38 }; return __func(_, this, arguments, Table_prototype_getById__4, 1, __frame, function __$Table_prototype_getById__4() {
        return _(null, new Query); }); };


    Table.prototype.update = function Table_prototype_update__5(columns, where, _) { var query, __this = this; var __frame = { name: "Table_prototype_update__5", line: 42 }; return __func(_, this, arguments, Table_prototype_update__5, 2, __frame, function __$Table_prototype_update__5() {

        if ((columns == null)) {
          columns = { }; } ;

        if ((where == null)) {
          where = { }; } ;

        query = new Query(__this.connection, __this.name);
        return query.update(columns, where, __cb(_, __frame, 9, 19, _, true)); }); };


    Table.prototype.del = function Table_prototype_del__6(where, _) { var query, __this = this; var __frame = { name: "Table_prototype_del__6", line: 54 }; return __func(_, this, arguments, Table_prototype_del__6, 1, __frame, function __$Table_prototype_del__6() {

        if ((where == null)) {
          where = { }; } ;

        query = new Query(__this.connection, __this.name);
        return query.del(where, __cb(_, __frame, 6, 19, _, true)); }); };


    Table.prototype.count = function Table_prototype_count__7(_) { var __frame = { name: "Table_prototype_count__7", line: 63 }; return __func(_, this, arguments, Table_prototype_count__7, 0, __frame, function __$Table_prototype_count__7() {
        return _(null, new Query); }); };


    Table.prototype.drop = function Table_prototype_drop__8(_) { var __this = this; var __frame = { name: "Table_prototype_drop__8", line: 67 }; return __func(_, this, arguments, Table_prototype_drop__8, 0, __frame, function __$Table_prototype_drop__8() {
        return __this.connection.execute(("DROP TABLE " + __this.name), [], __cb(_, __frame, 1, 29, _, true)); }); };


    return Table;

  })();

  module.exports = Table;

}).call(this);
