/*** Generated by streamline 0.10.10 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Query, Row, Table;

  Row = require("./Row");

  Query = require("./Query");

  Table = (function() {
    function Table(connection, name, columns, primary) {
      this.connection = connection;
      this.name = name;
      this.columns = columns;
      this.primary = ((primary != null) ? primary : []);
      con(this.columns); };


    Table.prototype.validateColummns = function(columnNames) {
      var invalids;
      if ((columnNames == null)) {
        columnNames = []; } ;

      invalids = columnNames.map((function(_this) {
        return function(c) {
          if ((_this.columns[c] == null)) {
            return c; }
           else {
            return null; } ; };


      })(this)).filter(function(a) {
        return (a != null); });

      if (!((invalids.length === 0))) {
        throw new Error(("Invalid column(s): " + invalids.join(", "))); } ; };



    Table.prototype.add = function Table_prototype_add__1(pairs, _) { var query, __this = this; var __frame = { name: "Table_prototype_add__1", line: 38 }; return __func(_, this, arguments, Table_prototype_add__1, 1, __frame, function __$Table_prototype_add__1() {

        __this.validateColummns(Object.keys(pairs));
        query = new Query(__this.connection, __this);
        return query.insert(pairs, __cb(_, __frame, 4, 19, _, true)); }); };


    Table.prototype.get = function Table_prototype_get__2(where, orderBy, _) { var query, __this = this; var __frame = { name: "Table_prototype_get__2", line: 45 }; return __func(_, this, arguments, Table_prototype_get__2, 2, __frame, function __$Table_prototype_get__2() {

        if ((where == null)) {
          where = { }; } ;

        if ((orderBy == null)) {
          orderBy = null; } ;

        __this.validateColummns(Object.keys(where));
        __this.validateColummns(((orderBy != null) ? orderBy.map(function(a) {
          if ((a[0] === "-")) {
            return a.slice(1); }
           else {
            return a; } ;

        }) : void 0));
        query = new Query(__this.connection, __this);
        return query.select(where, orderBy, __cb(_, __frame, 17, 19, _, true)); }); };


    Table.prototype.getUnsafe = function Table_prototype_getUnsafe__3(where, orderBy, _) { var query, __this = this; var __frame = { name: "Table_prototype_getUnsafe__3", line: 65 }; return __func(_, this, arguments, Table_prototype_getUnsafe__3, 2, __frame, function __$Table_prototype_getUnsafe__3() {

        if ((where == null)) {
          where = { }; } ;

        if ((orderBy == null)) {
          orderBy = null; } ;

        __this.validateColummns(Object.keys(where));
        __this.validateColummns(((orderBy != null) ? orderBy.map(function(a) {
          if ((a[0] === "-")) {
            return a.slice(1); }
           else {
            return a; } ;

        }) : void 0));
        query = new Query(__this.connection, __this, false);
        return query.select(where, orderBy, __cb(_, __frame, 17, 19, _, true)); }); };


    Table.prototype.all = function Table_prototype_all__4(_) { var __this = this; var __frame = { name: "Table_prototype_all__4", line: 85 }; return __func(_, this, arguments, Table_prototype_all__4, 0, __frame, function __$Table_prototype_all__4() {
        return __this.get(null, null, __cb(_, __frame, 1, 18, _, true)); }); };


    Table.prototype.update = function Table_prototype_update__5(columns, where, _) { var query, __this = this; var __frame = { name: "Table_prototype_update__5", line: 89 }; return __func(_, this, arguments, Table_prototype_update__5, 2, __frame, function __$Table_prototype_update__5() {

        if ((columns == null)) {
          columns = { }; } ;

        if ((where == null)) {
          where = { }; } ;

        __this.validateColummns(Object.keys(columns));
        __this.validateColummns(Object.keys(where));
        query = new Query(__this.connection, __this);
        return query.update(columns, where, __cb(_, __frame, 11, 19, _, true)); }); };


    Table.prototype.updateUnsafe = function Table_prototype_updateUnsafe__6(columns, where, _) { var query, __this = this; var __frame = { name: "Table_prototype_updateUnsafe__6", line: 103 }; return __func(_, this, arguments, Table_prototype_updateUnsafe__6, 2, __frame, function __$Table_prototype_updateUnsafe__6() {

        if ((columns == null)) {
          columns = { }; } ;

        if ((where == null)) {
          where = { }; } ;

        __this.validateColummns(Object.keys(columns));
        __this.validateColummns(Object.keys(where));
        query = new Query(__this.connection, __this, false);
        return query.update(columns, where, __cb(_, __frame, 11, 19, _, true)); }); };


    Table.prototype.del = function Table_prototype_del__7(where, _) { var query, __this = this; var __frame = { name: "Table_prototype_del__7", line: 117 }; return __func(_, this, arguments, Table_prototype_del__7, 1, __frame, function __$Table_prototype_del__7() {

        if ((where == null)) {
          where = { }; } ;

        __this.validateColummns(Object.keys(where));
        query = new Query(__this.connection, __this);
        return query.del(where, __cb(_, __frame, 7, 19, _, true)); }); };


    Table.prototype.delUnsafe = function Table_prototype_delUnsafe__8(where, _) { var query, __this = this; var __frame = { name: "Table_prototype_delUnsafe__8", line: 127 }; return __func(_, this, arguments, Table_prototype_delUnsafe__8, 1, __frame, function __$Table_prototype_delUnsafe__8() {

        if ((where == null)) {
          where = { }; } ;

        __this.validateColummns(Object.keys(where));
        query = new Query(__this.connection, __this, false);
        return query.del(where, __cb(_, __frame, 7, 19, _, true)); }); };


    Table.prototype.count = function Table_prototype_count__9(_) { var r, __this = this; var __frame = { name: "Table_prototype_count__9", line: 137 }; return __func(_, this, arguments, Table_prototype_count__9, 0, __frame, function __$Table_prototype_count__9() {

        return __this.connection.execute((("SELECT COUNT(*) AS C FROM \"" + __this.name) + "\""), [], __cb(_, __frame, 2, 26, function ___(__0, __1) { r = __1;
          return _(null, r[0].C); }, true)); }); };


    Table.prototype.empty = function Table_prototype_empty__10(_) { var __this = this; var __frame = { name: "Table_prototype_empty__10", line: 143 }; return __func(_, this, arguments, Table_prototype_empty__10, 0, __frame, function __$Table_prototype_empty__10() {
        return __this.connection.execute((("TRUNCATE TABLE \"" + __this.name) + "\""), [], __cb(_, __frame, 1, 29, _, true)); }); };


    return Table;

  })();

  module.exports = Table;

}).call(this);
